# File: .github/workflows/docker-deploy.yml (Optional CI/CD)
name: Docker Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t notes-app .

    - name: Save image as artifact
      run: |
        docker save notes-app > notes-app.tar
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: notes-app
        path: notes-app.tar
